### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by MMisery** [sc3/townsquare-flask#13]
The Readme states that the application should be using Python 3.5, but, as far as I can tell, the earliest slated release for that (as stated at https://www.python.org/dev/peps/pep-0478/) is in February 2015. Typo?

**Comment by wilbertom** [comment]
LOL

```
~/Code/sc3 wil
>>> python3.5
Python 3.5.0a0 (default:731b9653ef6b, Dec 22 2014, 20:34:46) 
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Yeah @MMisery you are right. We should stick to `3.4`.
